server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-server
  data:
    mongodb:
      port: 27017
      database: auth_server
      host: 192.168.25.129
  redis:
    host: 192.168.25.129
    port: 6379
security:
  oauth2:
    resource:
      filter-order: 3