server:
  port: 8763
  display-name: service-hi

spring:
  application:
    name: service-hi
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/

#安全配置
security:
  oauth2:
    resource:
      id: service-hi
      #指定用户信息地址
      user-info-uri: http://localhost:8769/auth/user
      prefer-token-info: false

